### ISSUE TITLE
Fails at first hurdle

### ISSUE THREAD

**Issue by GoodLug** [JacobLee23/riemann#9]
Using demo code:

>>> import riemann
>>> from riemann import Dimension

I get an error:

ImportError: cannot import name 'Dimension' from 'riemann' 

and indeed looking in riemann.py there is nothing named Dimension.

What am I doing wrong?

I'm using python 3.8.1.

**Comment by JacobLee23** [comment]
That's on me; I neglected to merge my latest branch. Things are still buggy, but be sure you're using the [latest version](https://pypi.org/project/riemann/1.0.0a1/) of `riemann` (v.1.0.0-a.1):

```console
$ pip install riemann==1.0.0a1
```

The README should be updated to reflect the new syntax.

**Comment by GoodLug** [comment]
Sorry, still not working:

AttributeError: module 'riemann' has no attribute 'rsum'

Looking at the code, there is def riemann_sum(...) so I think this is just a typo at one end or the other. 

Changing the code

>>> riemann.rsum(f, intervals, methods)
to 
>>> riemann.riemann_sum(f, intervals, methods)

does seem to do the trick and make it work.
